language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '9'

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - if ([ $TRAVIS_PULL_REQUEST == "false" ]); then
    docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH}-`date +%s` .;
    docker push settlemint/${PROJECT_NAME};
    fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
